# https://help.github.com/en/categories/automating-your-workflow-with-github-actions

on: [push, pull_request]

jobs:
  phpstan:
    name: "PHPStan"

    runs-on: ${{ matrix.operating-system }}

    strategy:
      fail-fast: false
      matrix:
        php-version:
          - "8.1"
          - "8.2"
        operating-system: [ubuntu-latest, windows-latest]

    steps:
      - name: "Checkout"
        uses: actions/checkout@v3

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          php-version: "${{ matrix.php-version }}"

      - name: "Install dependencies"
        run: "composer update --no-interaction --no-progress --ignore-platform-reqs"

      - name: "PHPStan"
        run: |
          composer install --ignore-platform-reqs
          vendor/bin/phpstan
